### ISSUE TITLE
 list index out of range 

### ISSUE THREAD

**Issue by tree0628** [brianoy/EEW_line_notify#1]
索引超出範圍 
magnitude = str(sys.argv[1]).replace("+","強").replace("-","弱")

**Comment by 0x6r1an0y** [comment]
是怎麼調用py檔案的? 這個error代表沒有傳入引數就直接去調用line_notify.py，如果要調用line_notify.py就必須透過earthquick.bat，而earthquick.bat又要再從地牛wakeup!裡面去做設定(即第四步~第七步)。
這個小專案年久失修，我才剛把readme跟其他東西補完整，先全部換成我新上傳的檔案，再按照新的流程試試看。
